### ISSUE TITLE
Allow passing in an already opened socket to listen on

### ISSUE THREAD

**Issue by ned** [plack/Plack-Runner#1]
I want to add a new option to pass in a socket file descriptor to listen on, for example

```perl
$runner->parse_options('--listen-sock', $sock_fd);
```

I need this because I want to ensure Plack::Runner is running on a free port, but I don't think there's a way to do that currently (that's guaranteed to be free from race conditions). What I'd like to be able to do is

```perl
my $server = Test::TCP->new(
    listen => 1,
    code => sub {
        my $socket = shift;
        my $sock_fd = fileno($socket);
        my $app = ...;
        my $runner = Plack::Runner->new;
        $runner->parse_options('--listen-sock', $sock_fd);
        $runner->run($app);
    }
);
my $port = $server->port;
```

**Comment by miyagawa** [comment]
This repo was created as an experiment but has never made it to CPAN. see https://github.com/plack/Plack/
